import os
import shutil
fin=open('index3.html',"r",encoding="UTF-8")
fout=open("index3_en.html","w",encoding="UTF-8")
for elem in fin:
    s=elem.replace("Sondaggio relativo al:","Sounding date and time: ")
    s=s.replace("Punti del Sondaggio","Sounding points")    
    s=s.replace("Nomogramma di Herlofson interattivo","Interactive Herlofson's nomogram")
    s=s.replace("Incolla un radiosondaggio da","Paste a sounding from")
    s=s.replace("Incolla","Paste")
    s=s.replace("Informazioni","Station information and sounding indices")
    s=s.replace("Risoluzione temperatura","Temperature resolution")
    s=s.replace("Quota di partenza","Starting altitude")
    s=s.replace("Temperatura di partenza","Starting temperature")
    s=s.replace("Sondaggi","Soundings")
    s=s.replace("Stato","State")
    s=s.replace("Località","Station")
    s=s.replace("Pressione","Pression")
    s=s.replace("Temperatura","Temperature")
    s=s.replace("Altitudine standard","Standard altitude")
    s=s.replace("Rugiada","DewPoint")
    s=s.replace("Curve","Curves")    
    s=s.replace("Adiabatiche secche","Dry adiabats")
    s=s.replace("Adiabatica secca","Dry adiabat")
    s=s.replace("Adiabatiche sature","Wet adiabats")
    s=s.replace("Adiabatica satura","Wet adiabat")
    s=s.replace("Stabilità assoluta","Total stability")    
    s=s.replace("Indicatori di Instabilità Atmosferica","Atmospheric Instability Indicators")
    s=s.replace("Scala umidit&agrave","Mix scale")
    s=s.replace("Quota isobare","Isobar altitudes")
    s=s.replace("Isoigrometriche","Isoiogrometrics")
    s=s.replace("Tropopausa","Tropopause")
    s=s.replace("Isobare","Isobars")
    s=s.replace("Isometriche","Isometrics")
    s=s.replace("Moti convettivi possibili","Possibility of convection")
    s=s.replace("Quantit&agrave di vapor acqueo bassa","Low quantity of vapor")
    s=s.replace("Moti convettivi poco probabili","Low possibility of convection")
    s=s.replace("Stabilit&agrave assoluta","Absolute stability")
    s=s.replace("Media 500 metri","Average of first 500m")
    s=s.replace("Stazione","Site")
    s=s.replace("Sondaggi","Soundings")
    s=s.replace("Indicatori di Instabilit&agrave Atmosferica","Atmospheric Instability Indicators")
    s=s.replace("Atmosferica","")
    s=s.replace("Linee T P","T P lines")
    s=s.replace("Temp rugiada","Dew-point temp")

    print(s,end="",file=fout)               
fin.close()
fout.close()

           
                
